name: snapshot build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          cache-dependency-path: |
            kotlin-js-store/yarn.lock
#      - name: build web
#        run: |
#          cd web
#          yarn
#          yarn build
#          cd ..
      - name: build
        run: ./gradlew prepareDevNodeModules clean build
      - name: publish
        run: ./scripts/publish-snapshot.sh
        env:
          PUNI_NPM_USER: ${{ secrets.PUNI_NPM_USER }}
          PUNI_NPM_PASS: ${{ secrets.PUNI_NPM_PASS }}
          PUNI_NPM_EMAIL: ${{ secrets.PUNI_NPM_EMAIL }}
